config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users do
    resources :workouts, only: [:index, :show, :new, :create, :edit, :update] do
      resources :workout_exercises, only: [:index, :edit, :update]
    end
    resources :exercises, only: [:index, :show, :new, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  has_many :workout_exercises
  has_many :workouts, through: :workout_exercises
  has_many :user_exercises
  has_many :users, through: :user_exercises
end

app/models/user.rb
class User < ApplicationRecord
  has_many :workouts
  has_many :user_exercises
  has_many :exercises, through: :user_exercises
  validates :user_name, :first_name, :last_name, :password, presence: true
  # validates :password_digest, presence: true, length: { minimum: 6 }
  has_secure_password

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

end

app/models/user_exercise.rb
class UserExercise < ApplicationRecord
  belongs_to :user
  belongs_to :exercise
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :workout_exercises
  has_many :exercises, through: :workout_exercises
  attr_accessor :muscles

  def generate_random_workout(equipment, muscle, intensity= 0, number= 8)
    if number.to_i % muscle.length == 0
      arr = []
      n = number.to_i/muscle.length
      muscle.count.times do |i|
        if equipment == "1"
          arr << Exercise.all.select {|exercise| exercise.muscle_group == muscle[i].downcase}.sample(n)
        else
          arr << Exercise.all.select {|exercise| exercise.muscle_group == muscle[i].downcase && exercise.equipment == false}.sample(n)
        end
      end
      arr.flatten
    end

  end
end

app/models/workout_exercise.rb
class WorkoutExercise < ApplicationRecord
  belongs_to :workout
  belongs_to :exercise
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_login

  private

  def check_login
    if !user_is_signed_in
      flash[:alert] = "Need to sign in"
      redirect_to login_path
    end
  end

  def user_is_signed_in
    if params[:user_id]
        session[:user_id] == params[:user_id].to_i && @user = User.find(session[:user_id])
    elsif params[:id]
      session[:user_id] == params[:id].to_i && @user = User.find(session[:user_id])
    else
      @user = User.find(session[:user_id])
    end
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  def index
    @exercises = Exercise.all
  end

  def show
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
      redirect_to exercise_path(@exercise)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @exercise.update(exercise_params)
      redirect_to exercise_path(@exercise)
    else
      render :edit
    end
  end

  def destroy
    @exercise.delete
    redirect_to home_path
  end


  private

  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:name, :muscle_group, :muscle_part, :equipment, :high_intensity)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_login, only: [:new, :create]

  def new
  end

  def create

    checking_user = User.find_by(user_name: params[:user_name])
    if checking_user != nil
      # binding.pry
      @user = checking_user.authenticate(params[:password])
    end
    if @user != false
      # binding.pry
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      # binding.pry
      flash[:alert] = "Incorrect username or password DUMBASS"
      redirect_to login_path
    end
  end

  def destroy
  reset_session
  redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :check_login, only: [:new, :create]
  # validates :user_name, uniqueness: true

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user.delete
    redirect_to root_path
  end


  private


  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :password, :user_type, :first_name, :last_name, :weight, :height, :body_fat, :bmi, :goal)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
skip_before_action :check_login, only: [:index]
  def index
  end

end

app/controllers/workout_exercises_controller.rb
class WorkoutExercisesController < ApplicationController

  def index
    # binding.pry
    @workout_exercises = WorkoutExercise.all.select { |workout_exercises| workout_exercises.workout_id == params[:workout_id].to_i}
    # binding.pry
  end

  # def show
  #   @workout_exercise = WorkoutExercise.find(params[:id])
  # end

  def edit

  end

  def update
    # binding.pry
    @workout_exercise = WorkoutExercise.find(params[:id])
    # binding.pry
    if @workout_exercise.update(weight: params[:weight], sets: params[:sets], reps: params[:reps], rest_time: params[:rest_time])
      # binding.pry
      redirect_to user_workout_workout_exercises_path(@user, params[:workout_id])
    else
      render :index
    end
  end

end

app/controllers/workouts_controller.rb
require 'pry'
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  def index
    @workouts = Workout.all.select { |workout| workout.user_id == @user.id }
    # @workouts.each do |workout|
    #   @muscles = (workout.exercises.each {|exercise| exercise.muscle_group}).uniq

  end

  def show
  end

  def new
    @muscle_groups = ["Chest", "Back", "Shoulders", "Biceps", "Triceps", "Legs", "Abs", "Full-Body"]
    @workout = Workout.new
  end

  def create
    @muscle_groups = ["Chest", "Back", "Shoulders", "Biceps", "Triceps", "Legs", "Abs", "Full-Body"]
    @workout = Workout.new(date: Date.today, user_id: @user.id)
    exercises = @workout.generate_random_workout(equipment= params[:equipment], muscle= params[:workout][:muscles])
    if @workout.save
      exercises.each do |exercise|

        @workout.workout_exercises.build(exercise_id: exercise.id).save
      end
      redirect_to user_workout_workout_exercises_path(@user, @workout)
    else
      render :new
    end
  end

  def edit
    @muscle_groups = ["Chest", "Back", "Shoulders", "Biceps", "Triceps", "Legs", "Abs", "Full-Body"]
  end

  def update
    if @workout.update(workout_params)
      redirect_to user_workout_path(@user, @workout)
    else
      render :edit
    end
  end

  def destroy
    @workout.destroy
    reset_session
    redirect_to root_path
  end

  private

  def set_workout
    @workout = Workout.find(params[:id])
  end

  def workout_params
    params.require(:workout).permit(:user_id, :date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercise.html.erb
<li>Exercise: <%= exercise.name %></li>
<li>Muscle used: <%= exercise.muscle_group %></li>
<li>Muscle detail: <%= exercise.muscle_part %></li>
<li>Need equipment: <%= exercise.equipment %></li>
<li>Intensity: <%= exercise.high_intensity %></li>

app/views/exercises/_form.html.erb
<%= form_for exercise do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :muscle_group %>
<%= f.text_field :muscle_group %>
<%= f.label :muscle_part %>
<%= f.text_field :muscle_part %>
<%= f.label :equipment %>
<%= f.text_field :equipment %>
<%= f.label :high_intensity %>
<%= f.text_field :high_intensity %>
<%= f.submit %>
<% end %>

app/views/exercises/edit.html.erb
<%= render partial: "form", locals: {exercise: @exercise} %>

app/views/exercises/index.html.erb
<ul>
  <%= render @exercises %>
</ul>

app/views/exercises/new.html.erb
<%= render partial: "form", locals: {exercise: @exercise} %>

app/views/exercises/show.html.erb
<%= render partial: "exercise", locals: {exercise: @exercise} %><br>

<%= link_to "Edit exercise", edit_exercise_path(@exercise) %><br>
<%= form_for @exercise, method: :delete do |f| %>
<%= f.submit "DELETE☠️" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your workouts, always with you.</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <nav class="navbar navbar-default navbar-fixed-top">
    <a class="navbar-brand" class="navbar-left"><%= image_tag "", width: 200 %></a>
    <div class="btn-group show">
      <% if session[:user_id] %>
      <% user = User.find(session[:user_id]) %>
          <button class="btn btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <a> Welcome, <%= user.full_name %></a>
          </button>
          <div class="dropdown-menu dropdown-toggle-split">
            <li><%= link_to "My Stats", user_path(user) %></li>
            <li><%= link_to "Create New Workout", new_user_workout_path(user) %></li>
            <li><%= link_to "Check My Workout Log", user_workouts_path(user) %></li>
            <li><%= link_to "Edit Profile", edit_user_path(user) %></li>
            <li><%= link_to "Sign Out", logout_path, method: 'delete' %></li>
      <% else %>
          <%= link_to "Log In ", login_path, class: 'btn-btn primary'  %>
      <% end %>
      </div>
    </div>
  </nav>

<%= yield %>

<br>
<br>
<br>

<div class="footer">
   <div class="container">
     <p>💪 Alvaro & Andress Fitness | All rights reserved💪</p>
   </div>
 </div>

  </body>
</html>

app/views/users/_form.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">


        <%= form_for user do |f| %>
        <div class="form-group">
          *<%= f.label :user_name %>
          <%= f.text_field :user_name %>
        </div>

        <div class="form-group">
          *<%= f.label :password %>
          <%= f.text_field :password %>
        </div>

        <div class="form-group">
          *<%= f.label :first_name %>
          <%= f.text_field :first_name %>
        </div>

        <div class="form-group">
          *<%= f.label :last_name%>
          <%= f.text_field :last_name %>
        </div>

        <div class="form-group">
          <%= f.label :weight %>
          <%= f.number_field :weight, value: 0, class: :text_field, step: :any %>
        </div>

        <div class="form-group">
          <%= f.label :height %>
          <%= f.number_field :height, value: 0, class: :text_field, step: :any %>
        </div>

        <div class="form-group">
          <%= f.label :body_fat %>
          <%= f.number_field :body_fat, value: 0, class: :text_field, step: :any %>
        </div>

        <div class="form-group">
          <%= f.label :bmi %>
          <%= f.number_field :bmi, value: 0, class: :text_field, step: :any %>
        </div>

        <div class="form-group">
          <%= f.label :goal %>
          <%= f.text_field :goal %>
        </div>

        <%= f.submit %>
        <% end %>
        
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="subtitle">
  <h1>Welcome, <%= "#{user.full_name}"%>. Here are your stats.</h1>
</div>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">User</th>
    </tr>

  </thead>
  <tbody>

    <tr>
      <th scope="row">Name</th>
      <td><%= user.first_name %></td>
    </tr>

    <tr>
      <th scope="row">Last Name</th>
      <td><%= user.last_name %></td>
    </tr>

    <tr>
      <th scope="row">Weight</th>
      <td><%= user.weight %></td>
    </tr>

    <tr>
      <th scope="row">Height</th>
      <td><%= user.height %></td>

    </tr>
    <tr>
      <th scope="row">Body Fat</th>
      <td><%= user.body_fat %></td>
    </tr>

    <tr>
      <th scope="row">BMI</th>
      <td><%= user.bmi %></td>
    </tr>

    <tr>
      <th scope="row">Goal</th>
      <td><%= user.goal %></td>
    </tr>

  </tbody>
</table>

app/views/users/edit.html.erb
<div class="subtitle">
  <h1>Edit Your Account</h1>
</div>
<%= render partial: "form", locals: {user: @user} %>

app/views/users/new.html.erb
  <div class="subtitle">
    <h1>Create A New Account</h1>
  </div>
  <%= render partial: "form", locals: {user: @user} %>

app/views/users/show.html.erb
<div class="card">

  <%= render partial: "user", locals: {user: @user} %>
<div class="row">

  <div class="col-md-3">
  <div>
    <%= link_to "Check My Workout Log", user_workouts_path(@user), class: 'btn btn-primary' %>
  </div>
</div>

<div class="col-md-3">
  <div>
    <%= link_to "Create a New Workout", new_user_workout_path(@user), class: 'btn btn-success' %>
  </div>
</div>

  <div class="col-md-3">
  <div>
    <%= link_to "Edit your profile", edit_user_path(@user), class: 'btn btn-warning' %>
  </div>
</div>

  <%= form_for @user, method: :delete do |f| %>
<div class="col-md-3">
  <div>
    <%= f.submit "Delete Profile", class: 'btn btn-danger' %>
  </div>
</end>

  <% end %>

  </div>
</div>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  <div class="main-header-image" style="background-image: url(/assets/fitness.jpg);">
    <div class="title">
      <h1>ALL YOUR WORKOUTS, IN ONE PLACE.</h1>
    </div>
  </div>

  <div class="container-fluid">

    <div class="card">
      <div class="card-block">
        <i class="fa fa-cog fa-spin fa-5x"></i>
        <h4 class="card-title">Create a custom workout</h4>
        <p class="card-text">Create a custom workout according to your goals.<br> Do what you like.</p>
      </div>
    </div>

    <div class="card">
      <div class="card-block">
        <i class="fa fa-pencil fa-5x"></i>
        <h4 class="card-title">Randomize your workout</h4>
        <p class="card-text">Get a new workout and get ready to be challenged. <br> Muscle confusion stimulates growth.</p>
      </div>
    </div>

    <div class="card">
      <div class="card-block">
        <i class="fa fa-gavel fa-5x"></i>
        <h4 class="card-title">Keep track and transform</h4>
        <p class="card-text">Your progress will be with you everywhere you go.</p>
      </div>
    </div>
  </div>

  <br>

  <%= link_to 'Get started', new_user_path, class: "btn btn-primary btn-block" %>


  </body>
</html>

app/views/workout_exercises/index.html.erb
<br>
<br>
<br>
<br>

<div class="subtitle">
  <h1>Enjoy Your Workout!</h1>
</div>

<br>
<br>
<% @workout_exercises.each do |w_exercise| %>
    <%= form_tag user_workout_workout_exercise_path(@user, w_exercise.workout, w_exercise), method: "patch" do %>

    <div class="row">

      <div class="col-md-2">
        <p><%= w_exercise.exercise.name %></p>
      </div>

      <div class="col-md-10">
        <%= label_tag :weight %>
        <%= text_field_tag :weight, w_exercise.weight.to_i  %>
        <%= label_tag :sets %>
        <%= text_field_tag :sets, w_exercise.sets.to_i %>
        <%= label_tag :reps %>
        <%= text_field_tag :reps, w_exercise.reps.to_i %>
        <%= label_tag :rest_time %>
        <%= text_field_tag :rest_time, w_exercise.rest_time.to_i %>
        <%= submit_tag %>
      </div>

  <% end %>
</div>
<% end %>

<br>
<%= link_to 'Finish Workout', user_workouts_path, class: "btn btn-primary btn-block" %>

app/views/workouts/_form.html.erb
<div class="card">
  <%= form_for [user, workout] do |f| %>
  <h3>Choose Up To 2 Muscles or a Full-Body Workout</h3>
  <% muscle_groups.each do |muscle_group| %>
  <%= f.label muscle_group %>
  <%= f.check_box :muscles, {multiple: true}, muscle_group, false %><br>
  <% end %><br>
  <%= f.label "Do you have equipment?" %>
  <%= check_box_tag(:equipment) %><br>
  <%= f.submit %>
  <% end %>
</div>

app/views/workouts/edit.html.erb
<%= render partial: "form", locals: {workout: @workout, muscle_groups: @muscle_groups, user: @user} %>

app/views/workouts/index.html.erb
<div class="subtitle">
  <h1>Here is Your Workout Log!<h1>
</div>

<div class="jumbotron">
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col"></th>
      </tr>

  </thead>
  <tbody>

    <% @workouts.each do |workout| %>

    <tr>
      <th scope="row">Workout Date</th>
      <td><%= link_to workout.date, user_workout_workout_exercises_path(@user, workout) %></td>
    </tr>

    <% muscles = (workout.exercises.map {|exercise| exercise.muscle_group}).uniq %>
    <% muscles.each do |muscle| %>

    <tr>
      <th scope="row">Muscles Worked</th>
      <td><%= muscle %></td>
    </tr>

    <% end %>
  <% end %>

    </tbody>
  </table>
<div>

app/views/workouts/new.html.erb
<div class="subtitle">
  <h1>Create a new workout!</h1>
</div>

<%= render partial: "form", locals: {workout: @workout, muscle_groups: @muscle_groups, user: @user} %>

app/views/workouts/show.html.erb
<h2><%= @workout.user.full_name %></h2>
<ul>
  <% @workout.exercises.each do |exercise| %>
  <li><%= exercise.name %><br></li>
  <% end %>
</ul>